version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - choco install opencover.portable
  - choco install codecov
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build --configuration Release --no-restore
test_script:
  - cmd: dotnet test  --configuration Release --no-build --no-restore --verbosity minimal --test-adapter-path:. --logger:Appveyor /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:MergeWith="../TestResults/coverage.json"  /p:CoverletOutputFormat=lcov
  # - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\Tests\bin\Debug\Tests.dll" -[Tests*]*" -output:".\Sanakan_coverage.xml"
  # - codecov -f "Sanakan_coverage.xml
cache:
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
deploy: off