image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: Sanakan.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\Tests\bin\Debug\Tests.dll" -filter:"+[Web*]* -[Tests*]*" -output:".\Sanakan_coverage.xml"
- codecov -f "Sanakan_coverage.xml