CREATE TABLE `figures` (
  `Id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `Dere` int NOT NULL,
  `Attack` int NOT NULL,
  `Health` int NOT NULL,
  `Defence` int NOT NULL,
  `Name` varchar(50) NOT NULL,
  `Title` varchar(50) NOT NULL,
  `IsFocus` tinyint(1) NOT NULL,
  `ExpCnt` double NOT NULL,
  `RestartCnt` int NOT NULL,
  `Character` bigint unsigned NOT NULL,
  `IsComplete` tinyint(1) NOT NULL,
  `PAS` int NOT NULL,
  `SkeletonQuality` int NOT NULL,
  `CompletionDate` datetime NOT NULL,
  `FocusedPart` int NOT NULL,
  `PartExp` double NOT NULL,
  `HeadQuality` int NOT NULL,
  `BodyQuality` int NOT NULL,
  `LeftArmQuality` int NOT NULL,
  `RightArmQuality` int NOT NULL,
  `LeftLegQuality` int NOT NULL,
  `RightLegQuality` int NOT NULL,
  `ClothesQuality` int NOT NULL,
  `GameDeckId` bigint unsigned NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_Figures_GameDeckId` (`GameDeckId`),
  CONSTRAINT `FK_Figures_GameDecks_GameDeckId` FOREIGN KEY (`GameDeckId`) REFERENCES `gamedecks` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci