CREATE TABLE `guilds` (
  `Id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `MuteRole` bigint unsigned NOT NULL,
  `ModMuteRole` bigint unsigned NOT NULL,
  `UserRole` bigint unsigned NOT NULL,
  `AdminRole` bigint unsigned NOT NULL,
  `GlobalEmotesRole` bigint unsigned NOT NULL,
  `WaifuRole` bigint unsigned NOT NULL,
  `NotificationChannel` bigint unsigned NOT NULL,
  `RaportChannel` bigint unsigned NOT NULL,
  `QuizChannel` bigint unsigned NOT NULL,
  `ToDoChannel` bigint unsigned NOT NULL,
  `NsfwChannel` bigint unsigned NOT NULL,
  `LogChannel` bigint unsigned NOT NULL,
  `GreetingChannel` bigint unsigned NOT NULL,
  `WelcomeMessage` varchar(50) NOT NULL,
  `WelcomeMessagePW` varchar(50) NOT NULL,
  `GoodbyeMessage` varchar(50) NOT NULL,
  `SafariLimit` bigint NOT NULL,
  `Supervision` tinyint(1) NOT NULL,
  `ChaosMode` tinyint(1) NOT NULL,
  `Prefix` varchar(50) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci