CREATE TABLE `guilds` (
  `Id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `MuteRoleId` bigint unsigned NOT NULL,
  `ModMuteRoleId` bigint unsigned NOT NULL,
  `UserRoleId` bigint unsigned DEFAULT NULL,
  `AdminRoleId` bigint unsigned DEFAULT NULL,
  `GlobalEmotesRoleId` bigint unsigned NOT NULL,
  `WaifuRoleId` bigint unsigned DEFAULT NULL,
  `NotificationChannelId` bigint unsigned NOT NULL,
  `RaportChannelId` bigint unsigned NOT NULL,
  `QuizChannelId` bigint unsigned NOT NULL,
  `ToDoChannelId` bigint unsigned NOT NULL,
  `NsfwChannelId` bigint unsigned NOT NULL,
  `LogChannelId` bigint unsigned NOT NULL,
  `GreetingChannelId` bigint unsigned NOT NULL,
  `WelcomeMessage` varchar(2000) DEFAULT NULL,
  `WelcomeMessagePM` varchar(2000) DEFAULT NULL,
  `GoodbyeMessage` varchar(2000) DEFAULT NULL,
  `SafariLimit` bigint unsigned NOT NULL,
  `SupervisionEnabled` tinyint(1) NOT NULL,
  `ChaosModeEnabled` tinyint(1) NOT NULL,
  `Prefix` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
