CREATE TABLE `usersstats` (
  `UserId` bigint unsigned NOT NULL,
  `ScLost` bigint NOT NULL,
  `IncomeInSc` bigint NOT NULL,
  `SlotMachineGames` bigint NOT NULL,
  `Tail` bigint NOT NULL,
  `Head` bigint NOT NULL,
  `Hit` bigint NOT NULL,
  `Misd` bigint NOT NULL,
  `RightAnswers` bigint NOT NULL,
  `TotalAnswers` bigint NOT NULL,
  `TournamentsWon` bigint NOT NULL,
  `UpgradedCardsCount` bigint NOT NULL,
  `SacrificedCardsCount` bigint NOT NULL,
  `DestroyedCardsCount` bigint NOT NULL,
  `UnleashedCardsCount` bigint NOT NULL,
  `ReleasedCards` bigint NOT NULL,
  `OpenedBoosterPacks` bigint NOT NULL,
  `OpenedBoosterPacksActivity` bigint NOT NULL,
  `YamiUpgrades` bigint NOT NULL,
  `RaitoUpgrades` bigint NOT NULL,
  `YatoUpgrades` bigint NOT NULL,
  `WastedTcOnCookies` bigint NOT NULL,
  `WastedTcOnCards` bigint NOT NULL,
  `UpgradedToSSS` bigint NOT NULL,
  `WastedPuzzlesOnCookies` bigint NOT NULL,
  `WastedPuzzlesOnCards` bigint NOT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `FK_UsersStats_Users_UserId` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
