CREATE TABLE `usersstats` (
  `Id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ScLost` bigint NOT NULL,
  `IncomeInSc` bigint NOT NULL,
  `SlotMachineGames` bigint NOT NULL,
  `Tail` bigint NOT NULL,
  `Head` bigint NOT NULL,
  `Hit` bigint NOT NULL,
  `Misd` bigint NOT NULL,
  `RightAnswers` bigint NOT NULL,
  `TotalAnswers` bigint NOT NULL,
  `TurnamentsWon` bigint NOT NULL,
  `UpgaredCards` bigint NOT NULL,
  `SacraficeCards` bigint NOT NULL,
  `DestroyedCards` bigint NOT NULL,
  `UnleashedCards` bigint NOT NULL,
  `ReleasedCards` bigint NOT NULL,
  `OpenedBoosterPacks` bigint NOT NULL,
  `OpenedBoosterPacksActivity` bigint NOT NULL,
  `YamiUpgrades` bigint NOT NULL,
  `RaitoUpgrades` bigint NOT NULL,
  `YatoUpgrades` bigint NOT NULL,
  `WastedTcOnCookies` bigint NOT NULL,
  `WastedTcOnCards` bigint NOT NULL,
  `UpgradedToSSS` bigint NOT NULL,
  `WastedPuzzlesOnCookies` bigint NOT NULL,
  `WastedPuzzlesOnCards` bigint NOT NULL,
  `UserId` bigint unsigned NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IX_UsersStats_UserId` (`UserId`),
  CONSTRAINT `FK_UsersStats_Users_UserId` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci